// StackNavigation.ts
type StackParamList = {
  Home: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  EmailSent: undefined;
  SignUp: undefined;
  GetStarted: undefined;
  Setpin: undefined;
  Setpin1: undefined;
  AllSet: undefined;
  MainScreen: undefined;
  Settings: undefined;
  Account: undefined;
  Export: undefined;
  Export1: undefined;
  Currency: undefined;
  Theme: undefined;
  Security: undefined;
  Language: undefined;
  Notification: undefined;
  Header: undefined;
  CreateBudget: undefined;
  Expense: undefined;
  Income: undefined;
  Transfer: undefined;
  FinancialReportExpense: undefined;
  FinancialReportBudget: undefined;
  FinancialReportQuote: undefined;
  FinancialReportIncome: undefined;
  FinancialReport: undefined;
  DetailTransaction_Expense: undefined;
  DetailTransaction_Income: undefined;
  DetailTransaction_Transfer: undefined;
};
export default StackParamList;
