// StackNavigation.ts
type StackParamList = {
  Home: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  EmailSent: { email: string };
  SignUp: undefined;
  GetStarted: undefined;
  Setpin: undefined;
  Setpin1: { FirstPin: string };
  AllSet: { title: string };
  MainScreen: undefined;
  Settings: undefined;
  Account: undefined;
  Export: undefined;
  Export1: undefined;
  Currency: undefined;
  Theme: undefined;
  Security: undefined;
  Language: undefined;
  Notification: undefined;
  Header: undefined;
  CreateBudget: {
    value: number;
    category: string;
    alert: boolean;
    percentage: number;
    index?: string;
    edit: boolean;
    header: string;
    month?: number;
    year?: number;
  };
  Expense: {
    amount: number;
    category: string;
    edit: boolean;
    title: string;
    wallet: string;
    url: string;
    frequency: string;
    endDate: string;
    endAfter: string;
    repeat: boolean;
    startDate: number;
    startMonth: number;
    weekly: string;
    type: string;
  };
  Income: {
    amount: number;
    category: string;
    edit: boolean;
    title: string;
    wallet: string;
    url: string;
    frequency: string;
    endDate: string;
    endAfter: string;
    repeat: boolean;
    startDate: number;
    startMonth: number;
    weekly: string;
    type: string;
  };
  Transfer: {
    amount: number;
    to: string;
    from: string;
    edit: boolean;
    title: string;
    id: string;
    url: string;
    type: string;
  };
  FinancialReportExpense: undefined;
  FinancialReportBudget: undefined;
  FinancialReportQuote: undefined;
  FinancialReportIncome: undefined;
  FinancialReport: undefined;
  DetailTransaction_Expense: undefined;
  DetailTransaction_Income: undefined;
  DetailTransaction_Transfer: undefined;
  DetailBudget: {
    category: any;
    remaining: number;
    progress: number;
    exceeded: boolean;
    index: number;
    total: number;
    percentage: number;
    alert: boolean;
  };
  DetailAccount: {
    wallet: string;
  };
  DisplayNotification: undefined;
  EnterPin: undefined;
  "Terms&Services": undefined;
  Privacy: undefined;
  AboutUs: undefined;
  Help: undefined;
  Tutorial: undefined;
  ForgotPin: undefined;
};
export default StackParamList;
