import { StyleSheet, Platform, StatusBar } from "react-native";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundColor,
      paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    expandedBackground: {
      backgroundColor: "rgba(187, 220, 212, 0.87)", // subtle green overlay
    },
    sortImage: {
      borderWidth: 1,
      borderColor: "grey",
      borderRadius: 5,
    },
    reportView: {
      flex: 0.1,
      alignItems: "center",
      justifyContent: "center",
    },
    transactionHead: {
      flex: 0.08,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      margin: 10,
      marginLeft: 10,
    },
    dropdownItems: {
      justifyContent: "center",
      //  height: 56,
    },
    financialReport: {
      width: "95%",
      height: 48,
      borderRadius: 5,
      backgroundColor: colors.financialReport,
      alignItems: "center",
      justifyContent: "space-between",
      padding: 15,
      flexDirection: "row",
    },
    reportText: {
      color: colors.reportText,
    },
    arrows: {
      flex: 0.05,
      justifyContent: "center",
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContainer: {
      width: "100%",
      height: "85%",
      backgroundColor: colors.backgroundColor,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      position: "absolute",
      bottom: 0,
    },
    filter: {
      flex: 0.1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "90%",
      marginTop: 20,
    },
    notiTitle: {
      fontFamily: "Inter",
      fontSize: Platform.OS === "ios" ? 18 : 20,
      fontWeight: Platform.OS === "ios" ? 500 : "bold",
      color: colors.color,
    },
    reset: {
      backgroundColor: colors.seeall,
      width: "18%",
      height: "60%",
      alignItems: "center",
      justifyContent: "center",
      borderColor: "grey",
      borderRadius: 30,
    },
    homeTitle: {
      fontFamily: "Inter",
      fontSize: Platform.OS === "ios" ? 14 : 16,
      color: "white",
    },
    FilterOptions: {
      flex: 0.2,
      width: "90%",
    },
    flatListContainer: {
      justifyContent: "center",
      height: "90%",
    },
    filterButton: {
      borderRadius: 20,
      borderWidth: 1,
      borderColor: "#D1D1D1",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
      marginRight: 10,
      width: "28%",
      padding: 4,
    },
    sortButton: {
      //  backgroundColor: "red",
      padding: 5,
      borderColor: colors.color,
      borderWidth: 1,
      borderRadius: 5,
    },
    filterButtonText: {
      fontSize: 14,
      fontWeight: "bold",
      color: "#555",
      width: Platform.OS === "ios" ? 70 : 78,
      textAlign: "center",
    },
    FilterCategory: {
      flex: 0.5,
      width: "100%",
      marginBottom: 20,
      marginLeft: "10%",
    },
    category: {
      margin: 10,
      borderColor: "#D1D1D1",
      padding: 11,
      paddingLeft: 15,
      paddingRight: 15,
      borderWidth: 1,
      borderRadius: 20,
    },
    Apply: {
      width: "100%",
      alignItems: "center",
      backgroundColor: "pink",
    },
    badgeCount: {
      position: "absolute",
      right: "5%",
      top: "8%",
      backgroundColor: "red",
      width: "5%",
      height: "40%",
      borderRadius: 10,
      zIndex: 100,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "white",
    },
    badgeCountText: {
      color: "white",
      fontSize: 10,
    },
    settingsOptions: {
      flexDirection: "row",
      height: "20%",
      alignItems: "center",
    },
    budgetText: {
      fontFamily: "Inter",
      fontSize: Platform.OS === "ios" ? 14 : 16,
      color: "grey",
      width: "70%",
      textAlign: "center",
    },
  });
