import { StyleSheet, Platform, StatusBar } from "react-native";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      // backgroundColor: colors.backgroundColor,
      paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    add: {
      flex: 1,
      justifyContent: "flex-end",
    },
    balanceView: {
      margin: 15,
    },
    balance: {
      fontFamily: "Inter",
      fontWeight: Platform.OS === "ios" ? 500 : 600,
      fontSize: Platform.OS === "ios" ? 16 : 18,
      color: "rgba(220, 234, 233, 0.6)",
    },
    error: {
      color: "rgb(255, 0, 17)",
      position: "absolute",
      bottom: -7,

      marginLeft: 10,
      fontFamily: "Inter",
      fontSize: 12,
      width: "90%",
    },
    attachment: {
      width: "90%",
      height: 56,
      color: colors.color,
      borderRadius: 16,
      borderColor: "rgba(133, 126, 126, 0.89)",
      borderWidth: 1,
      margin: 10,
      padding: 15,
      justifyContent: "center",
      borderStyle: "dashed",
      alignItems: "center",
      flexDirection: "row",
    },
    notiView: {
      flexDirection: "row",
      width: "100%",
      padding: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    noti: {
      width: "85%",
    },
    notiTitle: {
      fontFamily: "Inter",
      fontSize: Platform.OS === "ios" ? 18 : 20,
      fontWeight: Platform.OS === "ios" ? 500 : "bold",
      color: colors.color,
    },
    notiDes: {
      fontFamily: "Inter",
      fontSize: Platform.OS === "ios" ? 12 : 14,
      color: "grey",
      width: "65%",
    },
    switch: {
      transform: Platform.OS === "ios" ? [{ scaleX: 0.8 }, { scaleY: 0.8 }] : [{ scaleX: 1.5 }, { scaleY: 1.5 }],
    },
    amount: {
      fontFamily: "Inter",
      fontWeight: Platform.OS === "ios" ? 500 : 600,
      fontSize: 60,
      color: "white",
    },
    selection: {
      backgroundColor: colors.backgroundColor,
      borderTopStartRadius: "10%",
      borderTopRightRadius: "10%",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      padding: 5,
      paddingTop: 15,
      paddingBottom: 10,
    },
    textinput: {
      width: "90%",
      height: 60,
      color: colors.color,
      borderRadius: 16,
      borderColor: "rgba(241, 241, 250, 1)",
      borderWidth: 1,
      margin: 10,
      padding: 15,
      justifyContent: "center",
      fontSize: 16,
    },
    modalOverlay: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    modalContainer: {
      width: "100%",
      height: "25%",
      backgroundColor: "white",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      position: "absolute",
      bottom: 0,
    },
  });
