import { StyleSheet, StatusBar, Platform } from "react-native";
import { RFPercentage, RFValue } from "react-native-responsive-fontsize";
export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundColor,
      paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    textinput: {
      width: "90%",
      height: "70%",
      borderRadius: 16,
      borderColor: "rgba(241, 241, 250, 1)",
      borderWidth: 1,
      margin: 10,
      padding: 15,
      alignItems: "center",
      justifyContent: "center",
      color: colors.color,
      fontSize: 16,
    },
    input: {
      alignItems: "center",
      justifyContent: "space-evenly",
      //  marginTop: Platform.OS === "ios" ? 20 : 30,
      width: "100%",
      marginTop: 10,
      height: "33%",
      // backgroundColor: "yellow",
    },
    or: {
      color: "rgb(145, 145, 159)",
      margin: 10,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: 700,
    },
    GoogleView: {
      flexDirection: "row",
      height: 56,
      width: "90%",
      alignItems: "center",
      justifyContent: "center",
      borderColor: "rgb(233, 233, 241)",
      borderRadius: 16,
      borderWidth: 1,
    },
    Google: {
      height: 40,
      width: 40,
    },
    account: {
      margin: 15,
      color: "rgba(145, 145, 159, 1)",
      fontSize: 16,
      fontWeight: 500,
    },
    span: {
      color: "rgb(57, 112, 109)",
      textDecorationLine: "underline",
      fontSize: 16,
      fontWeight: 500,
    },
    textGoogle: {
      // paddingLeft: 10,
      color: colors.color,
      fontWeight: "bold",
      height: "100%",
      fontSize: Platform.OS === "android" ? RFValue(16) : RFValue(14),
      verticalAlign: "middle",
      alignItems: "center",
      width: "50%",
      textAlign: "center",
      lineHeight: 50,
    },
  });
