export const TransactionSchema = {
  name: "Transaction",
  properties: {
    _id: "string",
    amount: "double",
    description: "string",
    category: "string",
    wallet: "string",
    moneyCategory: "string",
    Date: "string",
    repeat: "bool",
    Frequency: "string?",
    endAfter: "string?",
    endDate: "date?",
    startDate: "int?",
    startMonth: "int?",
    startYear: "int?",
    synced: { type: "bool", default: false },
    pendingDelete: { type: "bool", default: false },
  },
  primaryKey: "_id",
};
