export const categoryMap = {
  Food: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Food.png"),
  Shopping: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Shopping.png"),
  Subscription: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Subscription.png"),
  Miscellaneous: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Miscellaneous.png"),
  Entertainment: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Entertainment.png"),
  Transportation: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Transportation.png"),
  Bills: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Bills.png"),
  Transfer: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Transfer.png"),
  Salary: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Salary.png"),
  "Passive Income": require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Passive Income.png"),
};
export const Month = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const CATEGORY_COLORS: Record<string, string> = {
  Food: "rgba(253, 60, 74, 1)",
  Transport: "yellow",
  Shopping: "rgba(252, 172, 18, 1)",
  Entertainment: "#6CCACF",
  Subscription: "rgba(127, 61, 255, 1)",
  Transportation: "yellow",
  Transfer: "rgba(0, 119, 255, 1)",
  Bills: "purple",
  Miscellaneous: "#2A7C6C",
  Salary: "rgba(0, 168, 107, 1)",
  "Passive Income": "rgba(13, 14, 15, 1)",
};
