export const categoryMap = {
  Food: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Food.png"),
  Shopping: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Shopping.png"),
  Subscription: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Subscription.png"),
  Miscellaneous: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Miscellaneous.png"),
  Entertainment: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Entertainment.png"),
  Transportation: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Transportation.png"),
  Bills: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Bills.png"),
  Transfer: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Transfer.png"),
  Salary: require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Salary.png"),
  "Passive Income": require("/Users/chicmic/Desktop/Project/ExpenseTracker/assets/Passive Income.png"),
};
export const Month = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
